## Target Guided Ordinal Encoding 
It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [12]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df = pd.DataFrame({
    'city': ['Bengalore', 'Delhi', 'Mumbai', 'Mumbai', 'Delhi', 'Bengalore'],
    'rent': [200, 150, 300, 250, 180, 320]
})
df

        city  rent
0  Bengalore   200
1      Delhi   150
2     Mumbai   300
3     Mumbai   250
4      Delhi   180
5  Bengalore   320

In [14]:
mean_price=df.groupby('city')['rent'].mean().to_dict()
mean_price

{'Bengalore': 260.0, 'Delhi': 165.0, 'Mumbai': 275.0}

In [16]:
df['city_encoded']=df['city'].map(mean_price)
df[['rent','city_encoded']]

   rent  city_encoded
0   200         260.0
1   150         165.0
2   300         275.0
3   250         275.0
4   180         165.0
5   320         260.0